<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require_once 'path.php';
init_cobalt('Add purchaseorder');
if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);

if(isset($_GET['filter_field_used']) && isset($_GET['filter_used']) && isset($_GET['page_from']))
{
    $page_from = htmlentities($_GET['page_from']);
    $filter_used = htmlentities($_GET['filter_used']);
    $filter_field_used = htmlentities($_GET['filter_field_used']);
}

if(xsrf_guard())
{
    extract($_POST);
    if($_POST['cancel']) 
    {
        log_action('Pressed cancel button', $_SERVER[PHP_SELF]);
        header("location: listview_purchaseorder.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }

    if($_POST['submit'])
    {
        log_action('Pressed submit button', $_SERVER[PHP_SELF]);

        $DateOfDelivery = $DateOfDelivery_year . '-' . $DateOfDelivery_month . '-' . $DateOfDelivery_day;
        $Date = $year . '-' . $month . '-' . $day;

        $_POST['DateOfDelivery'] = $DateOfDelivery;
        $_POST['Date'] = $Date;
        require_once 'validation_class.php';
        require_once 'subclasses/purchaseorder.php';
        $dbh_purchaseorder = new purchaseorder;
        $validator = new validation;

        $message .= $dbh_purchaseorder->sanitize($_POST);
        extract($_POST);

        if($dbh_purchaseorder->check_uniqueness($_POST)) ;
        else $message = "Record already exists with the same primary identifiers!";

        if($message=="")
        {
            $dbh_purchaseorder->add($_POST);
            $id = $dbh_purchaseorder->auto_id;
            require_once 'subclasses/orderdetails.php';
            $dbh_purchaseorder = new orderdetails;
            for($a=0; $a<$orderdetails_count;$a++)
            {
                
                $param = array(
                           'id'=>$id,
                           'Quantity'=>$cf_orderdetails_Quantity[$a],
                           'Inventory'=>$cf_orderdetails_Inventory[$a]
                              );
                $dbh_purchaseorder->add($param);
            }


            header("location: listview_purchaseorder.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
        }
    }
}
require_once 'subclasses/purchaseorder_html.php';
$html = new purchaseorder_html;
$html->draw_header('Add purchaseorder', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from);
$html->draw_controls('off',TRUE,'Add Record',TRUE);


$cf_orderdetails_Inventory_query = "SELECT inventory.id AS `New_id`, inventory.Name FROM inventory";
$cf_orderdetails_Inventory_list_value = "New_id";
$cf_orderdetails_Inventory_list_items = array('Name');

$multifield_settings = array(
                             'field_labels' => array('Quantity','Inventory'),
                             'field_controls' => array('draw_text_field_mf','draw_select_field_from_query_mf'),
                             'field_parameters' => array(
                                                    array('cf_orderdetails_Quantity','text'),
                                                    array($cf_orderdetails_Inventory_query, $cf_orderdetails_Inventory_list_value, $cf_orderdetails_Inventory_list_items,'cf_orderdetails_Inventory')
                                                        )
                            );
$html->draw_multifield_auto('Orderdetails', $multifield_settings, 'num_orderdetails', 'orderdetails_count');	


$html->draw_controls_multifield_end();

$html->draw_footer();